In [3]:
import pandas as pd
from pathlib import Path

In [4]:
PROJECT_ROOT = Path.cwd().parent
TMDB_RAW_DIR = PROJECT_ROOT / "data" / "raw" / "tmdb"

TMDB_MOVIES_PATH = TMDB_RAW_DIR / "tmdb_5000_movies.csv"
TMDB_CREDITS_PATH = TMDB_RAW_DIR / "tmdb_5000_credits.csv"

In [5]:
print(TMDB_MOVIES_PATH)
print(TMDB_CREDITS_PATH)

C:\Users\maseglo.com\movie-recommendation-system\data\raw\tmdb\tmdb_5000_movies.csv
C:\Users\maseglo.com\movie-recommendation-system\data\raw\tmdb\tmdb_5000_credits.csv

In [6]:
tmdb_movies = pd.read_csv(TMDB_MOVIES_PATH)
tmdb_credits = pd.read_csv(TMDB_CREDITS_PATH)

In [7]:
tmdb_movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [8]:
tmdb_credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [9]:
print("TMDB movies shape:", tmdb_movies.shape)
print("TMDB credits shape:", tmdb_credits.shape)

TMDB movies shape: (4803, 20)
TMDB credits shape: (4803, 4)

In [10]:
print("TMDB movies columns:")
print(tmdb_movies.columns)

print("\nTMDB credits columns:")
print(tmdb_credits.columns)

TMDB movies columns:
Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='str')

TMDB credits columns:
Index(['movie_id', 'title', 'cast', 'crew'], dtype='str')

In [11]:
print("TMDB movies data types:")
print(tmdb_movies.dtypes)

print("\nTMDB credits data types:")
print(tmdb_credits.dtypes)

TMDB movies data types:
budget                    int64
genres                      str
homepage                    str
id                        int64
keywords                    str
original_language           str
original_title              str
overview                    str
popularity              float64
production_companies        str
production_countries        str
release_date                str
revenue                   int64
runtime                 float64
spoken_languages            str
status                      str
tagline                     str
title                       str
vote_average            float64
vote_count                int64
dtype: object

TMDB credits data types:
movie_id    int64
title         str
cast          str
crew          str
dtype: object

In [12]:
tmdb_movies.isna().sum().sort_values(ascending=False)

homepage                3091
tagline                  844
overview                   3
runtime                    2
release_date               1
id                         0
budget                     0
genres                     0
original_title             0
popularity                 0
original_language          0
keywords                   0
production_countries       0
production_companies       0
spoken_languages           0
revenue                    0
status                     0
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [13]:
tmdb_credits.isna().sum().sort_values(ascending=False)

movie_id    0
title       0
cast        0
crew        0
dtype: int64

In [14]:
missing_percent_movies = tmdb_movies.isna().mean().sort_values(ascending=False) * 100
missing_percent_movies

homepage                64.355611
tagline                 17.572351
overview                 0.062461
runtime                  0.041641
release_date             0.020820
id                       0.000000
budget                   0.000000
genres                   0.000000
original_title           0.000000
popularity               0.000000
original_language        0.000000
keywords                 0.000000
production_countries     0.000000
production_companies     0.000000
spoken_languages         0.000000
revenue                  0.000000
status                   0.000000
title                    0.000000
vote_average             0.000000
vote_count               0.000000
dtype: float64

In [15]:
print("Duplicate rows in TMDB movies:", tmdb_movies.duplicated().sum())
print("Duplicate rows in TMDB credits:", tmdb_credits.duplicated().sum())

Duplicate rows in TMDB movies: 0
Duplicate rows in TMDB credits: 0

In [16]:
print("Duplicate movie IDs in TMDB movies:", tmdb_movies["id"].duplicated().sum())
print("Duplicate movie IDs in TMDB credits:", tmdb_credits["movie_id"].duplicated().sum())

Duplicate movie IDs in TMDB movies: 0
Duplicate movie IDs in TMDB credits: 0